# Generated by Django 5.2.9 on 2025-12-24 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_event_capacity_event_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="menus/")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="PromoCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "discount_text",
                    models.CharField(
                        default="Promo Applied",
                        help_text="Ej: 'Entrada VIP' o '20% OFF'",
                        max_length=100,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="reservation",
            name="promo_code",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
