# Generated by Django 5.2.9 on 2025-12-24 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_menu_promocode_reservation_promo_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="birth_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reservation",
            name="dni",
            field=models.CharField(default="00000000", max_length=20),
        ),
    ]
