# Generated by Django 5.2.9 on 2025-12-24 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_reservation_birth_date_reservation_dni"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reservation",
            name="guest_name",
        ),
        migrations.AddField(
            model_name="reservation",
            name="first_name",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="reservation",
            name="maternal_surname",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="reservation",
            name="paternal_surname",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
