# Generated by Django 5.2.9 on 2025-12-29 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_remove_reservation_guest_name_reservation_first_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="image",
            field=models.URLField(
                blank=True,
                help_text="Pegar enlace de Google Drive (Debe ser público)",
                max_length=500,
                null=True,
            ),
        ),
    ]
