# Generated by Django 5.2.9 on 2025-12-29 04:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_event_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="PromoCampaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "current_benefit",
                    models.CharField(help_text="Ej: '2 Shots Gratis'", max_length=200),
                ),
                (
                    "instagram_url",
                    models.URLField(
                        default="https://www.instagram.com/sabbath.bar.club?igsh=MXRucnJtcHR0aXNmYg%3D%3D&utm_source=qr"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="PromoTicket",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("dni", models.CharField(max_length=20)),
                ("qr_code", models.ImageField(blank=True, upload_to="promo_qrcodes/")),
                ("is_used", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tickets",
                        to="core.promocampaign",
                    ),
                ),
            ],
        ),
    ]
