# Generated by Django 5.2.9 on 2025-12-29 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_promocampaign_promoticket"),
    ]

    operations = [
        migrations.AddField(
            model_name="promocampaign",
            name="limit",
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name="promocampaign",
            name="manual_claims",
            field=models.IntegerField(default=0),
        ),
    ]
