# Generated by Django 4.2 on 2026-03-09 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_promocampaign_limit_promocampaign_manual_claims"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="menu",
            name="image",
            field=models.URLField(
                help_text="Pegar enlace de Google Drive (PDF o Imagen)", max_length=500
            ),
        ),
    ]
