# Generated by Django 4.2 on 2026-03-09 02:37

from django.db import migrations, models

NEW_IG_URL = "https://www.instagram.com/sabbatclub/"


def update_instagram_urls(apps, schema_editor):
    PromoCampaign = apps.get_model("core", "PromoCampaign")
    PromoCampaign.objects.all().update(instagram_url=NEW_IG_URL)


def reverse_update(apps, schema_editor):
    pass  # No revert needed


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_add_event_date_index"),
    ]

    operations = [
        migrations.AlterField(
            model_name="promocampaign",
            name="instagram_url",
            field=models.URLField(default=NEW_IG_URL),
        ),
        migrations.RunPython(update_instagram_urls, reverse_update),
    ]
